### ISSUE TITLE
python-x2go 

### ISSUE THREAD

**Issue by kewlfft** [muflone/pkgbuilds#3]
The python-x2go package has some python2 unnecessary dependencies due to the dependency of this package to epydoc. epydoc has been inactive for a while, it is recommended to replace it with pdoc.
Thanks for maintaining this package.

**Comment by kewlfft** [comment]
The package is now out of date, I can help by being co maintainer if you wish.

**Comment by muflone** [comment]
I've added you as co-maintainer in the AUR package.

I cannot be able to replace epydoc with pdoc as the current python-pdoc package doesn't seem to handle well html files or I'm unable to make it work

**Comment by kewlfft** [comment]
Appreciated, thanks very much
