### ISSUE TITLE
Please consider adding libredwg ?

### ISSUE THREAD

**Issue by luzpaz** [muflone/pkgbuilds#6]
Hey @muflone  
Would you consider adding yet another package to your list as maintainer: libredwg ? This is utilized by FreeCAD
 
```
GNU LibreDWG is a free C library to handle DWG files. It aims to be a free replacement for the OpenDWG libraries. DWG is the native file format of AutoCAD.
```

Current version is: v0.9 (beta)   
* Official site: https://savannah.gnu.org/projects/libredwg/  
* Github (mirror): https://github.com/LibreDWG/libredwg  
* License: GPL3 [Link](https://github.com/LibreDWG/libredwg/blob/master/COPYING) 
* Changelog/News: https://raw.githubusercontent.com/LibreDWG/libredwg/master/NEWS

* FreeBSD's port file: (currently v0.9) (https://svnweb.freebsd.org/ports/head/cad/libredwg/Makefile?view=markup&pathrev=513950
* OpenSuSe tumbleweed .spec file (currently v0.8)
https://build.opensuse.org/package/view_file/openSUSE:Factory/libredwg/libredwg.spec?expand=1

#### Packaging Status
[![Packaging status](https://repology.org/badge/vertical-allrepos/libredwg.svg?header=libredwg)](https://repology.org/project/libredwg/versions)

**Comment by muflone** [comment]
Hi @luzpaz 
I currently don't use libreswg and I don't use any tool which needs it.
I could try to package it but a package which needs it should be around, in order to test it and make it useful. Do you have any?

**Comment by luzpaz** [comment]
FreeCAD uses it as a way to import DWG files. FreeCAD is currently in the AUR

**Comment by muflone** [comment]
Unfortunately freecad doesn't work in my system with intel GPU.
I tried to package it, the build works fine but I cannot test it as it crashes for me at the startup

**Comment by muflone** [comment]
if you can use freecad along with libreswg I could try to package it

**Comment by luzpaz** [comment]
> Unfortunately freecad doesn't work in my system with intel GPU.
> I tried to package it in the past, the build works fine but I cannot test it as it crashes for me at the startup

Yea, FC is kinda a PITA to maintain. There is a lot of work on the dependency and packaging. GPU issues usually require update or downgrade of driver.

 
> if you can use freecad along with libredwg I could try to package it

Yes, and others will also benefit, so thank you!

**Comment by luzpaz** [comment]
> if you can use freecad along with libredwg I could try to package it

Yes please!
